### ISSUE TITLE
Basic set of components

### ISSUE THREAD

**Issue by dimitraz** [slant-website/breakpoint.css#3]
**Description**
Agree on a basic set of components for the minimum viable product

**Ideas** 
- grid
- forms
- images / avatars (circle, square, etc) 
- buttons
- headers
- banners (jumbotron like banner & notifications)? 
-  list (horizontal & vertical) 
- nav

**Comment by dimitraz** [comment]
@piccolazucca @kingsleyzissou add your ideas here

**Comment by kingsleyzissou** [comment]
I don't know about avatars - is it essential? Images on the other hand 100%

Maybe we should get a mood board going?

**Comment by piccolazucca** [comment]
We should definitely get a mood board going, but I think we will figure out which features to add along the way

**Comment by dimitraz** [comment]
For now it makes sense to define the list of components that we want to start out with. If we want to add anything at a later stage then we can but we should have a starting point

**Comment by kingsleyzissou** [comment]
True. Just seeing if there is anything that might be useful as a core

**Comment by kingsleyzissou** [comment]
I think these are the core features:
* Typography classes (it would be nice if this was solid and well thought out)
* Forms
    - Inputs
    - Input groups (possibly)
    - Textarea
    - Checkbox
    - Radio
    - Input UX features (i.e. red borders & error messages)
* Buttons
* Modal
* Container
* Lists/menus
* Drop-downs
* Flex wrapper/container
* Navbar
* Pagination
* Section
* Table
* Images
* Badges
* Alerts/notifications (not toast notifications)

And then these are nice to have, but may be too much:
* Card
* Breadcrumbs
* Off canvas
* Toast notifications (would require JS)

With the avatar, rather than having an avatar class, maybe we could have a .circle class that you could add to the image. That could be useful for multiple components.

So maybe it would be good to have a bunch of utility classes.
A nice example would be a utility class that adds margin or padding to an item.

**Comment by dimitraz** [comment]
I think a few of those are not needed to be honest. How often would you find yourself using a badge or a table in a small personal project? I would drop badges, tables, maybe sections (could be done with just padding helpers but I guess they would be useful to have), modals

**Comment by dimitraz** [comment]
@piccolazucca @kingsleyzissou 
Are we ok with this initial set of components (can add more as we go of course):

* Typography
* Forms
    - Inputs
    - Input groups (possibly)
    - Textarea
    - Checkbox
    - Radio
    - Input UX features (i.e. red borders & error messages)
* Buttons
* Grid
* Lists
* Navbar / menus
    - Drop downs
* Sections?
* Images
* Alerts/notifications

**Comment by kingsleyzissou** [comment]
Yeah, I think throw sections in! But I'm happy with that list.
Oh, I was thinking, I would add a select box option too under forms.

**Comment by dimitraz** [comment]
@kingsleyzissou ok will do.
@kingsleyzissou @piccolazucca ok so we'll start with these components and circle back when we want to extend them. So I'll close this for now 👍
